name: ci

on:
  push:
    branches:
      - "master"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: tonisormisson
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Update repo description
        uses: peter-evans/dockerhub-description@v5
        with:
          username: tonisormisson
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: peter-evans/dockerhub-description

